"""The only place in Grod that runs the `git` program.

Everything the platform knows about a repository passes through here, so this
module can later be replaced by an own implementation of the Git format
without touching the rest of the code (see rule 9 in CLAUDE.md).
"""

import asyncio
import os
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from uuid import UUID, uuid4

from grod.config import get_settings

# Field separator for --format output; unlikely to appear inside a commit.
FIELD_SEPARATOR = "\x1f"
RECORD_SEPARATOR = "\x1e"
LOG_FORMAT = FIELD_SEPARATOR.join(["%H", "%an", "%ae", "%aI", "%s"]) + RECORD_SEPARATOR
TREE_ENTRY_FIELDS = 4
SEARCH_FIELDS = 3
DIFF_STAT_FIELDS = 1
MAX_PATCH_LENGTH = 200_000
NUL = chr(0)  # git grep --null separates its fields with this byte
TAB = chr(9)
MAX_MATCH_LENGTH = 500
MAX_BLOB_BYTES = 2 * 1024 * 1024


class GitError(Exception):
    """The git program refused to do what it was asked."""


class RefNotFoundError(Exception):
    """No branch, tag or commit with that name."""


class PathNotFoundError(Exception):
    """No such path inside the repository at that revision."""


@dataclass(frozen=True)
class Ref:
    """A branch or a tag."""

    name: str
    commit: str


@dataclass(frozen=True)
class TreeEntry:
    """One item of a directory listing."""

    name: str
    path: str
    type: str  # "blob" or "tree"
    size: int | None
    # The name Git knows the contents by; empty where the caller did not ask.
    object_id: str = ""


@dataclass(frozen=True)
class SearchMatch:
    """One line of the repository that contains the phrase."""

    path: str
    line_number: int
    line: str


@dataclass(frozen=True)
class Commit:
    """One entry of the history."""

    hash: str
    author_name: str
    author_email: str
    authored_at: datetime
    subject: str


# A server never rewrites line endings: what was pushed is what comes back.
NO_EOL_CONVERSION = ("-c", "core.autocrlf=false", "-c", "core.eol=lf")

PROTECTION_FILE = "grod-protected-branches"

# Git runs this before accepting a push. It refuses deleting a protected
# branch and refuses rewriting its history.
PRE_RECEIVE_HOOK = """#!/bin/sh
# Generated by Grod. Do not edit; the platform rewrites this file.
protected="$GIT_DIR/grod-protected-branches"
[ -f "$protected" ] || exit 0
zero=0000000000000000000000000000000000000000
status=0

while read -r old new ref; do
    branch=${ref#refs/heads/}
    [ "$branch" = "$ref" ] && continue

    while IFS= read -r pattern; do
        [ -z "$pattern" ] && continue
        case "$branch" in
        $pattern)
            if [ "$new" = "$zero" ]; then
                echo "Grod: branch $branch is protected and cannot be deleted." >&2
                status=1
            elif [ "$old" != "$zero" ] && ! git merge-base --is-ancestor "$old" "$new"; then
                echo "Grod: branch $branch is protected; rewriting its history is refused." >&2
                status=1
            fi
            ;;
        esac
    done < "$protected"
done

exit $status
"""


def repository_path(project_id: UUID) -> Path:
    """Where the bare repository of a project lives.

    Always absolute. Git reads several of its settings relative to the
    repository it is working in, so a relative path handed to it would be
    joined to that repository a second time.
    """
    return (get_settings().repositories_path / f"{project_id}.git").resolve()


async def _run(
    *arguments: str,
    cwd: Path | None = None,
    stdin: bytes | None = None,
    env: dict[str, str] | None = None,
) -> bytes:
    """Run git and return its output, or raise with what it complained about."""
    settings = get_settings()
    process = await asyncio.create_subprocess_exec(
        settings.git_binary,
        *arguments,
        cwd=cwd,
        stdin=asyncio.subprocess.PIPE if stdin is not None else None,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        env={**os.environ, **env} if env else None,
    )
    stdout, stderr = await process.communicate(stdin)
    if process.returncode != 0:
        raise GitError(stderr.decode(errors="replace").strip())
    return stdout


async def _run_allowing_failure(*arguments: str, cwd: Path | None = None) -> tuple[int, bytes]:
    """Run git and return its exit code with its output, raising nothing."""
    settings = get_settings()
    process = await asyncio.create_subprocess_exec(
        settings.git_binary,
        *arguments,
        cwd=cwd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, _ = await process.communicate()
    return process.returncode or 0, stdout


async def create_repository(project_id: UUID, *, default_branch: str) -> Path:
    """Create an empty bare repository for a project."""
    path = repository_path(project_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    await _run("init", "--bare", f"--initial-branch={default_branch}", str(path))
    # git http-backend refuses pushes unless the repository allows them; the
    # platform has already decided who may write by the time git runs.
    await _run("config", "http.receivepack", "true", cwd=path)
    # The same rule written into the repository itself, so anything reaching
    # for it outside this module gets the bytes that were pushed.
    await _run("config", "core.autocrlf", "false", cwd=path)
    await _run("config", "core.eol", "lf", cwd=path)
    return path


async def delete_repository(project_id: UUID) -> None:
    """Remove a repository from disk."""
    path = repository_path(project_id)
    if path.exists():
        await asyncio.to_thread(_remove_tree, path)


def _remove_tree(path: Path) -> None:
    import shutil

    shutil.rmtree(path, ignore_errors=True)


async def is_empty(project_id: UUID) -> bool:
    """True when the repository has no commits yet."""
    output = await _run("for-each-ref", "--count=1", cwd=repository_path(project_id))
    return not output.strip()


async def list_refs(project_id: UUID, *, kind: str) -> list[Ref]:
    """Return the branches ("heads") or tags of a repository."""
    output = await _run(
        "for-each-ref",
        f"--format=%(refname:short){FIELD_SEPARATOR}%(objectname)",
        f"refs/{kind}/",
        cwd=repository_path(project_id),
    )
    refs: list[Ref] = []
    for line in output.decode().splitlines():
        name, _, commit = line.partition(FIELD_SEPARATOR)
        if name:
            refs.append(Ref(name=name, commit=commit))
    return refs


async def resolve_ref(project_id: UUID, ref: str) -> str:
    """Return the commit a branch, tag or hash points at."""
    try:
        output = await _run(
            "rev-parse", "--verify", f"{ref}^{{commit}}", cwd=repository_path(project_id)
        )
    except GitError as error:
        raise RefNotFoundError(ref) from error
    return output.decode().strip()


async def list_tree(project_id: UUID, *, ref: str, path: str = "") -> list[TreeEntry]:
    """List one directory of the repository at a revision."""
    commit = await resolve_ref(project_id, ref)
    target = f"{commit}:{path}" if path else f"{commit}:"
    try:
        output = await _run("ls-tree", "--long", "-z", target, cwd=repository_path(project_id))
    except GitError as error:
        raise PathNotFoundError(path) from error

    entries: list[TreeEntry] = []
    for record in output.decode().split("\0"):
        if not record:
            continue
        # Format: <mode> <type> <object> <size>\t<name>
        head, _, name = record.partition("\t")
        fields = head.split()
        if len(fields) < TREE_ENTRY_FIELDS:
            continue
        _, object_type, _, size = fields[:TREE_ENTRY_FIELDS]
        entries.append(
            TreeEntry(
                name=name,
                path=f"{path}/{name}" if path else name,
                type=object_type,
                size=None if size == "-" else int(size),
            )
        )
    return sorted(entries, key=lambda entry: (entry.type != "tree", entry.name.lower()))


async def list_files(project_id: UUID, *, ref: str, limit: int) -> list[TreeEntry]:
    """List every file of a revision, folders walked through.

    Used by whatever has to look at a repository whole, such as scanning it
    for secrets; the limit keeps one enormous repository from taking the run.
    """
    commit = await resolve_ref(project_id, ref)
    output = await _run("ls-tree", "-r", "--long", "-z", commit, cwd=repository_path(project_id))

    entries: list[TreeEntry] = []
    for record in output.decode(errors="replace").split(NUL):
        if not record or len(entries) >= limit:
            break
        head, _, path = record.partition("	")
        fields = head.split()
        if len(fields) < TREE_ENTRY_FIELDS:
            continue
        _, object_type, object_id, size = fields[:TREE_ENTRY_FIELDS]
        if object_type != "blob":
            continue
        entries.append(
            TreeEntry(
                name=path.rsplit("/", 1)[-1],
                path=path,
                type=object_type,
                size=None if size == "-" else int(size),
                object_id=object_id,
            )
        )
    return entries


async def read_blob(project_id: UUID, *, ref: str, path: str) -> bytes:
    """Return the contents of one file at a revision."""
    commit = await resolve_ref(project_id, ref)
    try:
        return await _run("cat-file", "blob", f"{commit}:{path}", cwd=repository_path(project_id))
    except GitError as error:
        raise PathNotFoundError(path) from error


async def blob_size(project_id: UUID, *, ref: str, path: str) -> int:
    """Return the size of a file without reading it."""
    commit = await resolve_ref(project_id, ref)
    try:
        output = await _run("cat-file", "-s", f"{commit}:{path}", cwd=repository_path(project_id))
    except GitError as error:
        raise PathNotFoundError(path) from error
    return int(output.decode().strip())


async def list_commits(
    project_id: UUID, *, ref: str, limit: int, skip: int = 0, path: str | None = None
) -> list[Commit]:
    """Return the history of a revision, newest first."""
    commit = await resolve_ref(project_id, ref)
    arguments = [
        "log",
        f"--format={LOG_FORMAT}",
        f"--max-count={limit}",
        f"--skip={skip}",
        commit,
    ]
    if path:
        arguments += ["--", path]
    output = await _run(*arguments, cwd=repository_path(project_id))

    return _parse_commits(output)


def _parse_commits(output: bytes) -> list[Commit]:
    """Turn the output of git log into commits."""
    commits: list[Commit] = []
    for record in output.decode().split(RECORD_SEPARATOR):
        cleaned = record.strip("\n")
        if not cleaned:
            continue
        commit_hash, author_name, author_email, authored_at, subject = cleaned.split(
            FIELD_SEPARATOR
        )
        commits.append(
            Commit(
                hash=commit_hash,
                author_name=author_name,
                author_email=author_email,
                authored_at=datetime.fromisoformat(authored_at).astimezone(UTC),
                subject=subject,
            )
        )
    return commits


async def search(project_id: UUID, *, ref: str, query: str, limit: int) -> list[SearchMatch]:
    """Find lines containing a phrase, the way `git grep` does."""
    commit = await resolve_ref(project_id, ref)
    try:
        output = await _run(
            "grep",
            "--line-number",
            "-I",  # skip binary files
            "--null",
            "--fixed-strings",
            "--ignore-case",
            "-e",
            query,
            commit,
            cwd=repository_path(project_id),
        )
    except GitError:
        # git grep answers with a failure when nothing matches.
        return []

    prefix = f"{commit}:"
    matches: list[SearchMatch] = []
    for line in output.decode(errors="replace").splitlines():
        parts = line.split(NUL)
        if len(parts) < SEARCH_FIELDS:
            continue
        path, number, text = parts[0], parts[1], NUL.join(parts[2:])
        matches.append(
            SearchMatch(
                path=path.removeprefix(prefix),
                line_number=int(number),
                line=text[:MAX_MATCH_LENGTH],
            )
        )
        if len(matches) >= limit:
            break
    return matches


async def write_protection(project_id: UUID, patterns: list[str]) -> None:
    """Store the protected-branch rules and the hook that enforces them."""
    path = repository_path(project_id)
    rules = "".join(f"{pattern}\n" for pattern in patterns)
    (path / PROTECTION_FILE).write_text(rules, encoding="utf-8", newline="\n")

    hooks = path / "hooks"
    hooks.mkdir(parents=True, exist_ok=True)
    hook = hooks / "pre-receive"
    # The hook is a shell script, so it must keep Unix line endings.
    hook.write_text(PRE_RECEIVE_HOOK, encoding="utf-8", newline="\n")
    hook.chmod(0o755)


async def set_default_branch(project_id: UUID, branch: str) -> None:
    """Point HEAD of a bare repository at a branch."""
    await _run("symbolic-ref", "HEAD", f"refs/heads/{branch}", cwd=repository_path(project_id))


@dataclass(frozen=True)
class FileChange:
    """One file changed between two revisions."""

    path: str
    additions: int
    deletions: int
    binary: bool
    patch: str


@dataclass(frozen=True)
class MergeOutcome:
    """What happened when two branches were merged."""

    merged: bool
    commit: str | None
    conflicts: list[str]
    # Where the target stood when the merge was built; a queue has to know,
    # because the result is only good while the target has not moved.
    base: str = ""


async def merge_base(project_id: UUID, first: str, second: str) -> str:
    """Return the commit where two branches last agreed."""
    try:
        output = await _run("merge-base", first, second, cwd=repository_path(project_id))
    except GitError as error:
        raise RefNotFoundError(f"{first}..{second}") from error
    return output.decode().strip()


async def commits_between(project_id: UUID, *, base: str, head: str, limit: int) -> list[Commit]:
    """Return the commits that head has and base does not."""
    await resolve_ref(project_id, base)
    await resolve_ref(project_id, head)
    output = await _run(
        "log",
        f"--format={LOG_FORMAT}",
        f"--max-count={limit}",
        f"{base}..{head}",
        cwd=repository_path(project_id),
    )
    return _parse_commits(output)


async def diff(project_id: UUID, *, base: str, head: str, max_files: int) -> list[FileChange]:
    """Return the changes head brings on top of base, file by file."""
    common = await merge_base(project_id, base, head)
    path = repository_path(project_id)

    stats = await _run("diff", "--numstat", "-z", common, head, cwd=path)
    changes: list[FileChange] = []
    fields = stats.decode(errors="replace").split(NUL)
    index = 0
    while index + DIFF_STAT_FIELDS <= len(fields) + 1 and len(changes) < max_files:
        record = fields[index]
        if not record:
            break
        added, removed, name = record.split("\t")
        index += 1
        # A rename is spelled as two extra fields with the old and new name.
        if name == "":
            name = fields[index + 1] if index + 1 < len(fields) else ""
            index += 2

        binary = added == "-" or removed == "-"
        patch = b""
        if not binary:
            patch = await _run("diff", "--unified=3", common, head, "--", name, cwd=path)
        changes.append(
            FileChange(
                path=name,
                additions=0 if binary else int(added),
                deletions=0 if binary else int(removed),
                binary=binary,
                patch=patch.decode(errors="replace")[:MAX_PATCH_LENGTH],
            )
        )
    return changes


def _conflicting_paths(lines: list[str]) -> list[str]:
    """Pull the conflicting paths out of what merge-tree printed.

    The first line is the tree, then one line per conflicting stage as
    "mode oid stage<tab>path", then a blank line and the messages for people.
    """
    paths: list[str] = []
    for line in lines[1:]:
        if not line:
            break
        _, _, name = line.partition(TAB)
        if name and name not in paths:
            paths.append(name)
    return paths


async def merge_preview(
    project_id: UUID,
    *,
    target: str,
    source: str,
    message: str,
    author_name: str,
    author_email: str,
) -> MergeOutcome:
    """Build the commit that merging would make, without moving anything.

    A merge queue needs exactly this: the result has to be tested before the
    branch is allowed to move onto it.
    """
    path = repository_path(project_id)
    target_commit = await resolve_ref(project_id, target)
    source_commit = await resolve_ref(project_id, source)

    # merge-tree leaves conflicts on stdout and exits with 1, which is not a failure.
    code, output = await _run_allowing_failure(
        "merge-tree", "--write-tree", target_commit, source_commit, cwd=path
    )
    lines = output.decode(errors="replace").splitlines()
    if code != 0:
        return MergeOutcome(
            merged=False, commit=None, conflicts=_conflicting_paths(lines), base=target_commit
        )

    tree = lines[0].strip()
    commit_output = await _run(
        "-c",
        f"user.name={author_name}",
        "-c",
        f"user.email={author_email}",
        "commit-tree",
        tree,
        "-p",
        target_commit,
        "-p",
        source_commit,
        "-m",
        message,
        cwd=path,
    )
    merge_commit = commit_output.decode().strip()
    return MergeOutcome(merged=True, commit=merge_commit, conflicts=[], base=target_commit)


async def merge_branches(
    project_id: UUID,
    *,
    target: str,
    source: str,
    message: str,
    author_name: str,
    author_email: str,
) -> MergeOutcome:
    """Merge source into target and move the target branch onto the result."""
    outcome = await merge_preview(
        project_id,
        target=target,
        source=source,
        message=message,
        author_name=author_name,
        author_email=author_email,
    )
    if not outcome.merged or outcome.commit is None:
        return outcome

    await point_branch(project_id, branch=target, commit=outcome.commit, expected=outcome.base)
    return outcome


async def point_branch(
    project_id: UUID, *, branch: str, commit: str, expected: str | None = None
) -> None:
    """Move a branch onto a commit, only if it still stands where it was.

    The old value is handed to Git, so a branch that moved in the meantime is
    left alone instead of being quietly overwritten.
    """
    arguments = ["update-ref", f"refs/heads/{branch}", commit]
    if expected is not None:
        arguments.append(expected)
    await _run(*arguments, cwd=repository_path(project_id))


async def delete_branch(project_id: UUID, branch: str) -> None:
    """Remove a branch. Used for the throwaway ones a merge queue makes."""
    await _run("update-ref", "-d", f"refs/heads/{branch}", cwd=repository_path(project_id))


@dataclass(frozen=True)
class FileEdit:
    """One file to write, or to take out when the content is None."""

    path: str
    content: bytes | None


class StaleBranchError(Exception):
    """Somebody else moved the branch while this edit was being made."""


async def commit_files(
    project_id: UUID,
    *,
    branch: str,
    edits: list[FileEdit],
    message: str,
    author_name: str,
    author_email: str,
    parent: str | None,
) -> str:
    """Write files into a branch and return the commit that did it.

    A bare repository has no working copy, so the change is built the way Git
    builds one underneath: the contents become objects, a throwaway index
    turns into a tree, and the tree becomes a commit. The branch is moved only
    if it still stands where the caller last saw it, so two people editing the
    same file cannot quietly overwrite each other.
    """
    path = repository_path(project_id)
    head = await _current_tip(project_id, branch)
    if head != parent:
        raise StaleBranchError(branch)

    # The index lives beside the repository and is thrown away afterwards.
    index = path / f"index-{uuid4().hex}"
    environment = {"GIT_INDEX_FILE": str(index)}
    try:
        if head is not None:
            await _run("read-tree", head, cwd=path, env=environment)
        for edit in edits:
            await _stage(path, environment, edit)
        tree = (await _run("write-tree", cwd=path, env=environment)).decode().strip()
    finally:
        index.unlink(missing_ok=True)

    arguments = [
        "-c",
        f"user.name={author_name}",
        "-c",
        f"user.email={author_email}",
        "commit-tree",
        tree,
        "-m",
        message,
    ]
    if head is not None:
        arguments += ["-p", head]
    commit = (await _run(*arguments, cwd=path)).decode().strip()

    reference = f"refs/heads/{branch}"
    if head is None:
        await _run("update-ref", reference, commit, "", cwd=path)
    else:
        await _run("update-ref", reference, commit, head, cwd=path)
    return commit


async def _current_tip(project_id: UUID, branch: str) -> str | None:
    """Where a branch stands now, or None when it is not there yet."""
    try:
        return await resolve_ref(project_id, branch)
    except RefNotFoundError, GitError:
        return None


EMPTY_OBJECT = "0" * 40


async def _stage(path: Path, environment: dict[str, str], edit: FileEdit) -> None:
    """Put one file into the throwaway index, or take it out of it.

    Both go in through --index-info, the one form of update-index that asks
    for no working copy; a bare repository has none to give it.
    """
    if edit.content is None:
        record = f"000000 {EMPTY_OBJECT}\t{edit.path}\n"
    else:
        blob = (
            (await _run("hash-object", "-w", "--stdin", cwd=path, stdin=edit.content))
            .decode()
            .strip()
        )
        record = f"100644 {blob}\t{edit.path}\n"
    await _run("update-index", "--index-info", cwd=path, env=environment, stdin=record.encode())


async def copy_from(target_id: UUID, source_id: UUID, *, branch: str = "") -> None:
    """Fill an empty repository with what another one holds.

    Used when somebody starts a project from a template: the copy is made on
    the server, so nobody has to clone and push a repository by hand.
    """
    source = repository_path(source_id)
    target = repository_path(target_id)
    refspec = (
        f"+refs/heads/{branch}:refs/heads/{branch}" if branch else "+refs/heads/*:refs/heads/*"
    )
    await _run("fetch", "--no-tags", str(source), refspec, cwd=target)


async def archive(project_id: UUID, commit: str, *, path: str | None = None) -> bytes:
    """Return the tree at a commit as a tar archive, or one folder of it.

    A runner takes the code this way instead of cloning, so it needs no Git
    credentials of its own; publishing a site copies a folder the same way.
    """
    # Without this, Git would hand the files over with the line endings of
    # whoever runs the server, and a repository would come out of the archive
    # different from what was pushed into it.
    arguments = [*NO_EOL_CONVERSION, "archive", "--format=tar", commit]
    if path:
        arguments += ["--", path]
    try:
        return await _run(*arguments, cwd=repository_path(project_id))
    except GitError as error:
        # Git says the same thing for a missing commit and a missing path, so
        # the caller is told which one it asked about.
        if path:
            raise PathNotFoundError(path) from error
        raise RefNotFoundError(commit) from error
